#!/usr/bin/bash

# hr - print a horizontal rule (line)
#
# Usage:  hr [options]
#
# Options:
#   -c --character c  Use character c to use to draw the rule.
#                     Default: ─
#                              (line drawing caracter)
#   -h --help         Print this help and quit.
#   -w --width n      Set the width of the rule to n characters.
#                     Defaults to the tmux pane width (or 80 characters, if not
#                     in a tmux pane).

# Extract switches
. <(process-options $0)

[ -z "$(option w)" ] &&
  option w value $(coalesce $(tmux display -p "#{pane_width}") 80)
printf -v spaces '%*s' $(option w)
echo ${spaces// /$(option c)}
