#!/usr/bin/bash

declare -A o
o=(
  [f]="\n"
)
help=$(<<HELP cat
repos-gh - list repos hosted in GitHub

Usage:  repos-gh [options] [<fullName regex>]

Lists non-archived Kiwibank GitHub repositories that have a full name that
matches the <fullName regex> regular expression.  If no regular expression is
provided, all the non-archived Kiwibank repos will be listed.

Options:
  -f --OFS c        Use character c as the output field seperator.
                    Default: ${o[f]}
  -h --help         Print this help and quit.

HELP
)

# Extract switches
opts=$(<<<$help perl -ne '
  /^\s*-(\w+)\s+--([\w-]+)(\s+[a-z-]+)?/ or next;
  push @sht, $1.($3 && ":");
  push @lng, $2.($3 && ":");
  END {print "-o", join("", @sht), " --long ", join(",", @lng)}'
)
eval set -- $(getopt $opts -- "$@")
for opt
do
  case "$opt" in
    -f|--OFS)
      o[f]=$2
      ;;
    -h|--help)
      <<<$help cat
      exit 0
      ;;
  esac
  shift 1
done
[ "$1" == "--" ] && shift

regex=\"$(sed 's/"/\\"/g' <<<"${1:-.}")\"
regex_flags=\"${2}\"
gh search repos \
  --owner=Kiwibank \
  --archived=false \
  --json=fullName \
  --limit 1000 \
  --jq="
      map(
        select(
          (.fullName | test(\"$x\$\"; \"i\"))
          and
          (.fullName | test($regex; $regex_flags))
        )
        | .fullName
      )
      | sort
      | .[]
    " |
  perl -e'$,="'${o[f]}'"; print map {chop; $_} <>';
